#!/bin/bash
# ایجاد مسیر دایرکتوری اگر وجود ندارد
mkdir -p ~/.jupyter

# افزودن تنظیمات به فایل کانفیگ
echo "c.NotebookApp.allow_origin = '*'" >> ~/.jupyter/jupyter_notebook_config.py
echo "c.NotebookApp.disable_check_xsrf = True" >> ~/.jupyter/jupyter_notebook_config.py
